
[general]
	power_up_pattern_notification = true
	fully_repaired_alert = true
	lightning_rod_alert = true
	strat_for_next_round = true

	[general.overlay]
		scale = 1.0
		overlay_x = 7
		enabled = true
		strat_for_next_round = false
		overlay_y = 75

	[general.alien_arcadium]
		power_up_pattern_notification = false
		notify_grow_round_in_party_chat = false
		notify_grow_round = false
		pregame_info = false
		fully_repaired_alert = true
		lightning_rod_alert = true

	[general.fun]
		the_puncher_alert = true
		the_puncher_alert_in_party_chat = true
		"victory!!!_alert" = true

[overlay]
	scale = 1.0
	overlay_x = 0
	enabled = true
	overlay_y = 61
	strat = false

[messages]
	hide_revive_messages = false
	"hide_player_leave/rejoin_messages" = false
	hide_power_up_pickup_messages = false
	hide_gold_received_messages = false
	hide_knockdown_messages = false
	hide_open_area_messages = false
	hide_lucky_chest_messages = false
	hide_window_repair_messages = true
	hide_target_hit_messages = true

[zombies]
	power_up_pattern_notification = true
	fully_repaired_alert = true

	[zombies.general]
		power_up_pattern_notification = true
		fully_repaired_alert = true
		notify_next_round_power_up = false
		notify_next_round_power_up_in_party_chat = false

	[zombies.overlay]
		scale = 1.0
		overlay_x = 7
		enabled = true
		strat_for_next_round = true
		overlay_y = 108
		strat = true

	[zombies.alien_arcadium]
		cornering_spot_in_party_chat = false
		cornering_waypoints = false
		notify_grow_round_in_party_chat = false
		power_up_pattern_notification = true
		notify_grow_round = true
		pregame_info = false
		notify_next_round_power_up = true
		lightning_rod_alert = true
		notify_next_round_power_up_in_party_chat = false

	[zombies.fun]
		the_puncher_alert = false
		"victory!!!_alert" = false

[alien_arcadium]
	cornering_waypoints = false
	power_up_pattern_notification = true
	grow_round_alert_in_party_chat = false
	o1_alert = true
	pregame_info = false
	notify_next_round_power_up = true
	skill_alert = true
	notify_next_round_power_up_in_party_chat = false
	notify_camp = true
	grow_round_alert = true
	cornering_spot_in_party_chat = false
	notify_camp_in_party_chat = false
	notify_grow_round_in_party_chat = true
	giants_alert = true
	notify_grow_round = true
	giants_alert_in_party_chat = false
	lightning_rod_alert = true
	"insta_touched_alert_(grow_round)" = true

[party_chat]
	"insta_touched_alert_(grow_round)_in_party_chat" = false
	notify_camp_in_party_chat = false
	grow_round_alert_in_party_chat = false
	o1_alert_in_party_chat = true
	giants_alert_in_party_chat = true
	the_puncher_alert_in_party_chat = true
	notify_next_round_power_up_in_party_chat = false

